[package]
name = "indicatif"
description = "A progress bar and cli reporting library for Rust"
version = "0.11.0"
keywords = ["cli", "progress", "pb", "colors", "progressbar"]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
license = "MIT"
repository = "https://github.com/mitsuhiko/indicatif"
documentation = "https://docs.rs/indicatif"
readme = "README.md"
edition = "2018"
exclude = ["screenshots/*"]

[dependencies]
parking_lot = "0.8.0"
regex = "1"
lazy_static = "1"
number_prefix = "0.3"
console = ">=0.7.5, <1.0.0"
rayon = { version = "1.0", optional = true }

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = ["wincon", "processenv", "winbase"]

[dev-dependencies]
rand = "0"
futures = "0.1"
tokio-core = "0.1"

[features]
default = []
with_rayon = ["rayon"]
